### ISSUE TITLE
StreamRoles not defined - not working anymore?

### ISSUE THREAD

**Issue by bjajoh** [Ar-Ray-code/picamera_ros2#3] opened 2023-08-25 17:31 UTC
Thanks for your work! @Ar-Ray-code 

However I sadly can't get it compiling with the current libcamera version.. :(

`/home/ubuntu/ros2_ws/src/lccv/src/libcamera_app.cpp:83:9: error: ‘StreamRoles’ was not declared in this scope; did you mean ‘StreamRole’?
   83 |         StreamRoles stream_roles = { StreamRole::StillCapture, StreamRole::Raw };
      |         ^~~~~~~~~~~
      |         StreamRole`

I guess the interface has changed?
Do you know how to fix it?

**Comment by bjajoh** [comment] 2023-08-25 17:56
Resolved here: https://github.com/kbarni/LCCV/pull/23

**Comment by Ar-Ray-code** [comment] 2023-08-26 01:03
Thanks for your report.

I think it's exactly as you say. This repository is based on v0.03, but the current libcamera is probably v0.1.0.

So, Your problem may be caused by API corruptions.

Please also see this [docs](https://git.libcamera.org/libcamera/libcamera.git/commit/?h=v0.1.0).

<br>

If you can solve yourself, I look forward to your pull-request.

**Comment by Ar-Ray-code** [comment] 2024-01-03 09:47
I used [christian-nils/picamera_ros2](https://github.com/christian-nils/picamera_ros2) to confirm rpi-bookworm & ROS2-iron support and it works!
I'm looking to merge. What do you think? @christian-nils

**Comment by Ar-Ray-code** [comment] 2024-01-14 02:59
This PR (https://github.com/Ar-Ray-code/picamera_ros2/pull/5) was merged and resolved.

**Closed as completed by Ar-Ray-code** 2024-01-14 02:59 UTC

**Comment by christian-nils** [comment] 2024-01-15 07:45
Hi @Ar-Ray-code !
Sorry I did not reply earlier, it seemed to be working when I made the PR, so I hope that should still work! Have a good one!
